configure docker compose for llm models

diff --git a/next/Dockerfile b/next/Dockerfile
--- a/next/Dockerfile
+++ b/next/Dockerfile
@@ -1,24 +1,39 @@
 FROM node:18-alpine AS base
 RUN npm i -g pnpm
 
-FROM base AS dependencies
+FROM base AS deps
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
-COPY package.json pnpm-lock.yaml ./
-RUN pnpm install
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
 
 FROM base AS build
 WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN mkdir -p /app
-COPY --from=dependencies /app/node_modules /app/node_modules
+# RUN mkdir -p /app
 RUN pnpm build
 RUN pnpm prune --prod
 
+
 FROM base AS deploy
 WORKDIR /app
-RUN mkdir -p /app
-COPY --from=build /app/.next ./dist
-COPY --from=build /app/node_modules ./node_modules
-
+ENV NODE_ENV production
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+COPY --from=build /app/public ./public
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static
+COPY --from=build /app/node_modules/next/dist/compiled/jest-worker ./node_modules/next/dist/compiled/jest-worker
+USER nextjs
 EXPOSE 3000
-CMD ["node", "dist/main"]
+ENV PORT 3000
+CMD ["node", "server.js"]
